# Generated by Django 5.0.4 on 2024-04-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Restaurant',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='soups',
        ),
    ]
