# Generated by Django 5.0.4 on 2024-04-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_remove_orders_restaurant_remove_orders_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
