# Generated by Django 5.0.4 on 2024-04-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Item',
        ),
    ]
